<template>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">
    <path fill="currentColor" d="M512 320 192 704h639.936z" />
  </svg>
</template>

<script lang="ts" setup>
// generated by scripts/generate.ts
defineOptions({
  name: 'CaretTop',
})
</script>
