<template>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">
    <path fill="currentColor" d="m512 128 288 320H224zM224 576h576L512 896z" />
  </svg>
</template>

<script lang="ts" setup>
// generated by scripts/generate.ts
defineOptions({
  name: 'DCaret',
})
</script>
