<template>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">
    <path
      fill="currentColor"
      d="M192 352h640l64 544H128zm128 224h64V448h-64zm320 0h64V448h-64zM384 288h-64a192 192 0 1 1 384 0h-64a128 128 0 1 0-256 0"
    />
  </svg>
</template>

<script lang="ts" setup>
// generated by scripts/generate.ts
defineOptions({
  name: 'GoodsFilled',
})
</script>
